version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "dev"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "npm"
